language: python
# Existing Python versions
python:
  - 3.5
#  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt
  - python setup.py install --no-binaries
script:
  - python setup.py test -a "--verbose"
after_success:
  - coveralls
